# Generated by Django 2.1.5 on 2019-02-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default='No description', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(default='N/A'),
        ),
    ]
