# Generated by Django 2.1.5 on 2019-02-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190208_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is where the content of the post will go'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(default='A simple description will suffice', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(default='For example: https://www.roblox.com/NewLogin'),
        ),
    ]
