# Generated by Django 2.1.7 on 2019-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190210_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hotel_Main_Img',
            field=models.ImageField(default='No Image', upload_to='images/'),
        ),
    ]
