# Generated by Django 2.1.7 on 2019-02-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190215_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hotel_Main_Img',
        ),
    ]
