# Generated by Django 2.1.7 on 2019-02-17 19:49

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_hotel_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(default='This is where the content of the post will go'),
        ),
    ]
